// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed_fetch_update.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const markFeedFetch = `-- name: MarkFeedFetch :exec
UPDATE feeds 
SET updated_at = $1,
last_fetched_at = $1
WHERE feeds.id = $2
`

type MarkFeedFetchParams struct {
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) MarkFeedFetch(ctx context.Context, arg MarkFeedFetchParams) error {
	_, err := q.db.ExecContext(ctx, markFeedFetch, arg.UpdatedAt, arg.ID)
	return err
}
